// 8x8 픽셀 아이콘 (x = 채움). 액션/음식 키와 동일한 이름으로 조회한다.
export const PIXEL_ICONS: Record<string, string[]> = {
  // --- 액션 ---
  feed: [
    "........",
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  snack: [
    "........",
    "..xxxx..",
    ".xxx.xx.",
    ".xxxxxx.",
    ".xx.xxx.",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  study: [
    "........",
    ".xxxxxx.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".x.xx.x.",
    ".xxxxxx.",
    "........",
  ],
  exercise: [
    "........",
    "x......x",
    "xx....xx",
    "xxxxxxxx",
    "xxxxxxxx",
    "xx....xx",
    "x......x",
    "........",
  ],
  selfDev: [
    "...xx...",
    "...xx...",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    ".xx..xx.",
    ".x....x.",
    "........",
  ],
  read: [
    "........",
    ".xxxxxx.",
    ".xxxxxx.",
    ".x....x.",
    ".xxxxxx.",
    ".x....x.",
    ".xxxxxx.",
    "........",
  ],
  play: [
    "........",
    "..xxxx..",
    ".xx.xxx.",
    ".xxxx.x.",
    ".x.xxxx.",
    ".xxx.xx.",
    "..xxxx..",
    "........",
  ],
  bath: [
    "...x....",
    "...x....",
    "..xxx...",
    "..xxx...",
    ".xxxxx..",
    ".xx.xx..",
    "..xxx...",
    "........",
  ],
  nap: [
    "........",
    "........",
    ".x....x.",
    ".xxxxxx.",
    "xxxxxxxx",
    "x......x",
    "........",
    "........",
  ],
  sleep: [
    "..xxxx..",
    ".xxxx...",
    ".xx.....",
    ".xx.....",
    ".xx.....",
    ".xxxx...",
    "..xxxx..",
    "........",
  ],

  // --- 음식 ---
  homeMeal: [
    "........",
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  cafeteria: [
    "........",
    "xxxxxxxx",
    "x.xx.x.x",
    "x.xx.x.x",
    "xxxxxxxx",
    "........",
    "........",
    "........",
  ],
  convenience: [
    "...x....",
    "..xxx...",
    ".xxxxx..",
    ".xx.xx..",
    "xxxxxxx.",
    "xxxxxxx.",
    "........",
    "........",
  ],
  fastfood: [
    "........",
    ".xxxxxx.",
    "xxxxxxxx",
    ".x.xx.x.",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    "........",
  ],
  salad: [
    "........",
    ".x.xx.x.",
    ".xxxxxx.",
    "xxxxxxxx",
    "xxxxxxxx",
    ".xxxxxx.",
    "..xxxx..",
    "........",
  ],
  coffee: [
    "........",
    ".xxxxx.x",
    ".xxxxxxx",
    ".xxxxx.x",
    ".xxxxx..",
    ".xxxxx..",
    "..xxx...",
    "........",
  ],

  // --- UI ---
  lock: [
    "..xxxx..",
    ".x....x.",
    ".x....x.",
    "xxxxxxxx",
    "xxx..xxx",
    "xxx..xxx",
    "xxxxxxxx",
    "........",
  ],
  check: [
    "........",
    "......x.",
    ".....xx.",
    "x...xx..",
    "xx.xx...",
    ".xxx....",
    "..x.....",
    "........",
  ],
  heart: [
    "........",
    ".xx.xx..",
    "xxxxxxx.",
    "xxxxxxx.",
    ".xxxxx..",
    "..xxx...",
    "...x....",
    "........",
  ],
  bolt: [
    "...xx...",
    "..xx....",
    ".xxx....",
    "xxxxxx..",
    "...xxx..",
    "..xx....",
    ".xx.....",
    "........",
  ],
  star: [
    "...xx...",
    "...xx...",
    ".xxxxxx.",
    "xxxxxxxx",
    ".xxxxxx.",
    ".xx..xx.",
    ".x....x.",
    "........",
  ],
};
